### ISSUE TITLE
如果要同步同一个mysql中的多个库、多个表该怎么配置？

### ISSUE THREAD

**Issue by xiaosagehua** [wj596/go-mysql-transfer#6]
如果要同步同一个mysql中的多个库、多个表该怎么配置？

**Comment by wj596** [comment]
像下面这样：


```
rule:
  -
    schema: eseap #数据库名称
    table: t_user #表名称
    column_underscore_to_camel: true 
    value_encoder: json  
    redis_structure: string 
    redis_key_prefix: USER_
  -
    schema: eseap #数据库名称
    table: t_sign #表名称
    column_underscore_to_camel: true 
    value_encoder: json  
    redis_structure: string 
    redis_key_prefix: SIGN_
  -
    schema: gojob #数据库名称
    table: t_triggered #表名称
    column_underscore_to_camel: true 
    value_encoder: json  
    redis_structure: string 
    redis_key_prefix: TRIGGERED_
```
